"""Write reports/validation_report.md from reports/metrics.json so every number comes from the run."""
import json
import pandas as pd
from src import config as C


def table(rows: list[dict], cols: list[str] | None = None) -> str:
    df = pd.DataFrame(rows)
    df = df[cols] if cols else df
    return df.round(3).to_markdown(index=False)


def main() -> None:
    m = json.loads((C.REPORTS / "metrics.json").read_text())
    r, thr = m["results"], m["threshold"]
    fin = r[m["final_kind"]]
    be = fin["at_break_even"]
    costs = pd.DataFrame(m["costs"])
    at = costs[costs["threshold"] == thr].iloc[0]
    models = pd.DataFrame([{"model": k, "pr_auc": v["pr_auc"], "roc_auc": v["roc_auc"], "brier": v["brier"],
                            "accuracy@0.5": v["accuracy"], "recall@0.5": v["recall"]} for k, v in r.items()])
    ops = pd.DataFrame([{"model": k, **{a: v["at_break_even"][a] for a in ["accuracy", "precision", "recall", "f1", "tp", "fp", "tn", "fn"]}} for k, v in r.items()])
    d = m["drift"]
    lines = [
        "# Validation report", "",
        "All numbers below are generated by `python -m src.train` and `python -m src.report`.", "",
        "## 1. Dataset and split",
        f"- Labelled orders after removing duplicate partner-feed rows: {m['total_train_rows']}. Test orders: {m['test_rows']}.",
        f"- Train period: Apr 2025 to Mar 2026 ({m['train_n']} orders). Validation period: Apr to Jun 2026 ({m['valid_n']} orders, {m['valid_pos']} returns, rate {m['valid_rate']:.1%}).",
        "- The hidden test period is Jul to Sep 2026, so validation trains on the past and predicts a later quarter.",
        "- Return rate is about 11 percent. A model that never flags anything is 88.5 percent accurate, which is why accuracy is not the target.", "",
        "## 2. Model comparison (validation period)", models.round(3).to_markdown(index=False), "",
        f"Final model: **{m['final_kind']}**. It has the best PR-AUC, is simple to explain and its probabilities are well calibrated "
        f"(mean predicted {m['mean_pred_valid']:.3f} against actual {m['valid_rate']:.3f}), so no extra calibration was added. "
        "The class-weighted XGBoost has a much worse Brier score because weighting distorts probabilities, so it cannot be priced in rupees.", "",
        f"PR-AUC of the final model: {fin['pr_auc']:.3f} (95 percent bootstrap interval {m['pr_auc_ci'][0]:.3f} to {m['pr_auc_ci'][1]:.3f}). "
        f"The no-skill PR-AUC is {r['dummy']['pr_auc']:.3f}. ROC-AUC {fin['roc_auc']:.3f}.", "",
        f"## 3. Metrics at the policy threshold ({thr})", ops.round(3).to_markdown(index=False), "",
        f"Confusion matrix of the final model at {thr}: TP {be['tp']}, FP {be['fp']}, TN {be['tn']}, FN {be['fn']}. "
        f"Accuracy at this threshold is {be['accuracy']:.3f}; at 0.5 it is {fin['accuracy']:.3f}. Neither reaches 95 percent.", "",
        "## 4. Business cost (validation period, policy v4.1)",
        "- Return cost Rs 1,150. Confirmation call Rs 45. A call prevents about 35 percent of returns it is made on.",
        f"- A call pays off when probability x 0.35 x 1,150 > 45, i.e. probability above {thr}.",
        "- Cost = calls x 45 + (returns - 0.35 x returns caught) x 1,150. Saving is against doing nothing.", "",
        table(m["costs"], ["threshold", "calls", "tp", "fp", "fn", "precision", "recall", "total_cost", "saving_vs_no_action"]), "",
        f"At threshold {thr}: {int(at['calls'])} calls, saving Rs {at['saving_vs_no_action']:,.0f} over {m['valid_n']} orders "
        f"(about Rs {at['saving_vs_no_action'] / 3:,.0f} per month of validation). The curve is flat between 0.10 and 0.15, so the exact threshold matters little.",
        "Holding orders is not priced: the policy gives a 12 percent cancellation rate for holds but not the margin lost per cancellation. Cannot be determined from the provided data.", "",
        "## 5. Segment analysis (validation, flagged at the policy threshold)",
    ]
    for name, rows in m["segments"].items():
        lines += [f"**{name}**", table(rows), ""]
    lines += [
        "## 6. Error analysis",
        "- Misses (false negatives) concentrate in low-risk looking groups: prepaid UPI and EMI orders, non-Shield customers, ceiling fans and mixer grinders. Recall is lowest there.",
        "- False alarms concentrate where returns are common anyway: COD, Shield members, robot vacuums, customers with many prior orders. Many flagged orders are normal for those groups.",
        "- Gift orders are flagged far more often than their return rate justifies.",
        "- Error rates are stable across the three validation months.", "",
        "## 7. Drift, train versus test",
        f"- Share flagged: validation {d['valid_share_flagged']:.1%}, test {d['test_share_flagged_at_threshold']:.1%}. Mean score: validation {d['mean_score_valid']:.3f}, test {d['mean_score_test']:.3f}.",
        f"- COD share: train {d['train_cod_share']:.1%}, test {d['test_cod_share']:.1%}. Missing pincode share: train {d['train_pincode_default_share']:.1%}, test {d['test_pincode_default_share']:.1%}.",
        f"- Mean prior orders: train {d['train_prior_orders_mean']:.2f}, test {d['test_prior_orders_mean']:.2f}. No new categories or unknown customers and SKUs in test.",
        "- Test has `last_service_event_type` value INSTALL_BOOKED that never appears in train and no pickup times at all. This is one more reason those columns are not used.", "",
        "## 8. Limitations",
        "- Only one 3-month validation window. The interval above shows real uncertainty.",
        "- The 35 percent call effect comes from a spring pilot in the policy, not from this data.",
        "- Shield status comes from the current customer file and may have changed after the order. Signup dates are after the order date for 2,105 train rows, so tenure was not used.",
        "- Return label timing is unknown, so recent orders in train may be missing late returns.", "",
        "Figures are in `reports/figures/`.",
    ]
    (C.REPORTS / "validation_report.md").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
